### ISSUE TITLE
Assumption that students know ES6?

### ISSUE THREAD

**Issue by jsms90** [stevehopkinson/es6-challenge#1]
This is a cool idea for a morning challenge! Looks great :)

I'm sure many people will have seen the arrow function before. But I wouldn't assume that they are all aware of ES6 syntax. I get the feeling that this morning challenge is also designed as an introduction? But it might be worth adding an extra sentence or changing the wording in the description slightly, to make that a bit more obvious?

**Comment by stevehopkinson** [comment]
Good call – I added a line to make it clear that there was no prior knowledge necessary.
