### ISSUE TITLE
Clarify lack of need to do every template literal

### ISSUE THREAD

**Issue by ZooeyMiller** [stevehopkinson/es6-challenge#3]
In the SGC for this week one of the comments was that there were too many template literals to ES5-ify. 

I think a clarification in the instructions that once you get how to convert a certain type of syntax you don't have to convert _every_ instance of it to ES5.

**Comment by stevehopkinson** [comment]
To be honest, some of the template literals in the example don't need to be there at all. I'd suggest getting rid of the unnecessarily complicated template literals completely and just leaving in the sensible parts that didn't confuse people too much.

**Comment by stevehopkinson** [comment]
I've opened a PR with some fixes now – there's still one trickier template literal in there, but I think it's justified (and isn't right at the top, so shouldn't be an immediate roadblock for people). Reckon that'll do it?

I've fixed the shoddy (i.e. non-existent) semicolon use, too – I seem to remember that threw a few people off.

**Comment by ZooeyMiller** [comment]
Oh amazing! We were going to do this. Will review the PR later. I think what you've mentioned should cover it.

**Comment by stevehopkinson** [comment]
Ahh, sorry man – didn't mean to jump in there! I will not be offended if you ditch my PR and do it in a way that you feel more comfortable with (you're the ones who're going to be teaching it, after all).
